sudo: false

cache: bundler

bundler_args: --no-deployment

branches:
  only: master

rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

gemfile:
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.2.gemfile

script: bundle exec rake test

matrix:
  allow_failures:
    - rvm: ruby-head
